name: dart_dns
version: 0.1.4
homepage: https://github.com/mohn93/dns
description: A package for working with the DNS protocol.

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  dns-proxy: dns-proxy

dependencies:
  args: ^2.6.0
  meta: ^1.15.0
  better_dart_ip: ^0.1.1
  dart_raw: ^0.2.0
  universal_io: ^2.2.2

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.6.5